/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'service' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface PortfolioItem {
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface PricingPlan {
  'features' : Array<string>,
  'name' : string,
  'recommended' : boolean,
  'price' : number,
}
export interface Service {
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface _SERVICE {
  'addPortfolioItem' : ActorMethod<[string, string, string, string], undefined>,
  'addPricingPlan' : ActorMethod<
    [string, number, Array<string>, boolean],
    undefined
  >,
  'addService' : ActorMethod<[string, string, string], undefined>,
  'deletePortfolioItem' : ActorMethod<[string], undefined>,
  'deletePricingPlan' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllPricingPlans' : ActorMethod<[], Array<PricingPlan>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'seedData' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<[string, string, string, string], undefined>,
  'updatePortfolioItem' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updatePricingPlan' : ActorMethod<
    [string, number, Array<string>, boolean],
    undefined
  >,
  'updateService' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];